import streamlit as st
import pandas as pd
import numpy as np
import re
import io
from datetime import date

st.set_page_config(page_title="Egress Report Testing", layout="wide", page_icon="📤")
st.title("Egress Report Testing Tool")
st.caption("Internal QA for reports generated by Abett — validates output against spec before delivery.")

# ── DRILLDOWN HELPER ──────────────────────────────────────────────────────────
def drilldown(summary_df, key, caption="Click a row to see matching records."):
    st.caption(caption)
    sel = st.dataframe(
        summary_df,
        use_container_width=True,
        on_select="rerun",
        selection_mode="single-row",
        key=f"_dd_{key}",
    )
    rows = sel.selection.rows if sel.selection else []
    return summary_df.iloc[rows[0]] if rows else None


# ── FILE UPLOAD ───────────────────────────────────────────────────────────────
st.header("Upload Report Output")
c1, c2, c3 = st.columns(3)
delim_label = c1.selectbox("Delimiter", [
    "Comma (,)", "Pipe (|)", "Tab (\\t)",
    "Tilde (~)", "Semicolon (;)", "Colon (:)",
    'Double quote (")', "Single quote (')",
])
skip_space = c2.checkbox("Skip initial space")
no_quote   = c3.checkbox("Disable quoting")

DELIM = {
    "Comma (,)": ",", "Pipe (|)": "|", "Tab (\\t)": "\t",
    "Tilde (~)": "~", "Semicolon (;)": ";", "Colon (:)": ":",
    'Double quote (")': '"', "Single quote (')": "'",
}

uploaded = st.file_uploader("Upload report output (CSV or TXT)", type=["csv", "txt"])
if uploaded is None:
    st.info("Upload the report output file above to begin.")
    st.stop()

_file_id = f"{uploaded.name}_{uploaded.size}"
if st.session_state.get("_loaded_file_id") != _file_id:
    for _k in [
        "pop_results", "req_results", "filler_hits", "dummy_hits",
        "ev_hits", "ev_col_saved",
        "null_summary", "cond_null_hits",
        "len_summary", "len_col_saved",
        "upid_summary", "upid_tmp", "upid_id_cols", "upid_bio_cols",
        "dup_counts", "dup_key_cols",
        "dv_ord_results", "dv_ord_date_cols",
        "fin_recon_result", "fin_agg_result",
        "dob_hits", "dob_summary",
        "demo_sanity_hits", "demo_sanity_summary",
        "filter_boundary_result",
        "proc_cats", "proc_series", "proc_col_saved",
        "crossreport_hits",
    ]:
        st.session_state.pop(_k, None)
    st.session_state["_loaded_file_id"] = _file_id


@st.cache_data
def load_file(data, sep, skip, nq):
    kw = {"dtype": str, "keep_default_na": False, "na_values": [],
          "skipinitialspace": skip, "sep": sep}
    if nq:
        kw["quoting"] = 3
    return pd.read_csv(io.BytesIO(data), **kw)


try:
    raw = uploaded.read()
    df  = load_file(raw, DELIM[delim_label], skip_space, no_quote)
except Exception as e:
    st.error(f"Could not load file: {e}")
    st.stop()

st.success(f"Loaded **{df.shape[0]:,} rows × {df.shape[1]} columns**")
with st.expander("Quick preview (first 20 rows)"):
    st.dataframe(df.head(20), use_container_width=True)

cols       = df.columns.tolist()
total_rows = len(df)
st.divider()

# ── TABS ──────────────────────────────────────────────────────────────────────
tabs = st.tabs([
    "🔍 Data Explorer",
    "⚙️ Report Config & Setup",
    "📦 Data Completeness",
    "👤 Member Identification",
    "🗺 Data Mapping",
    "🚫 Null & Allowed Values",
    "🔧 Formatting & Logic",
    "✅ Sanity Checks",
])


# ════════════════════════════════════════════════════════════════════════════
# TAB 0 — Data Explorer
# ════════════════════════════════════════════════════════════════════════════
with tabs[0]:
    st.subheader("Data Explorer")
    st.caption("Select columns to display, then add column filters — works like Excel AutoFilter.")

    vis_cols = st.multiselect("Columns to display", cols, default=cols, key="vis_cols")
    if not vis_cols:
        st.warning("Select at least one column.")
    else:
        with st.expander("Column Filters", expanded=True):
            filter_on = st.multiselect("Add filters for columns", vis_cols, key="filter_on")
            filters = {}
            if filter_on:
                grid = st.columns(min(len(filter_on), 4))
                for i, fc in enumerate(filter_on):
                    v = grid[i % 4].text_input(fc, key=f"fv_{fc}", placeholder="type to filter…")
                    if v.strip():
                        filters[fc] = v.strip()

        view = df[vis_cols].copy()
        for fc, fv in filters.items():
            view = view[view[fc].astype(str).str.contains(re.escape(fv), case=False, na=False)]

        st.caption(f"Showing **{len(view):,}** of **{total_rows:,}** rows")
        st.dataframe(view, use_container_width=True, height=560)
        st.download_button(
            "Download filtered data as CSV",
            data=view.to_csv(index=False).encode(),
            file_name=f"filtered_{uploaded.name.rsplit('.',1)[0]}.csv",
            mime="text/csv",
        )

    st.divider()
    st.markdown("#### Unique Values by Column")
    uv_cols = st.multiselect("Columns to inspect", cols, key="uv_cols")
    excl_kw = st.text_input(
        "Exclude columns whose name contains (comma-separated, case-insensitive)",
        value="SSN, social", key="uv_excl_kw",
    )
    if st.button("Show unique values", key="btn_uv") and uv_cols:
        excl_terms = [t.strip().lower() for t in excl_kw.split(",") if t.strip()]
        for col in uv_cols:
            if any(t in col.lower() for t in excl_terms):
                st.markdown(f"**{col}** — *skipped (excluded keyword)*")
                continue
            uvals  = df[col].dropna().unique().tolist()
            counts = df[col].value_counts(dropna=False).reset_index()
            counts.columns = ["Value", "Count"]
            counts["%"] = (counts["Count"] / total_rows * 100).round(2)
            with st.expander(f"**{col}** — {len(uvals):,} unique values", expanded=len(uv_cols) == 1):
                st.dataframe(counts, use_container_width=True, height=min(400, 38 + len(counts) * 35))


# ════════════════════════════════════════════════════════════════════════════
# TAB 1 — Report Configuration & Setup
# ════════════════════════════════════════════════════════════════════════════
with tabs[1]:
    st.subheader("Report Configuration & Setup")

    # ── Filename ─────────────────────────────────────────────────────────────
    st.markdown("**Filename Validation**")
    fname    = uploaded.name
    has_year = bool(re.search(r'\b(19|20)\d{2}\b', fname))
    st.write(f"**Filename:** `{fname}`")
    col1, col2 = st.columns(2)
    col1.write(f"{'✅' if has_year else '❌'} 4-digit year present in filename")
    ext = fname.rsplit(".", 1)[-1].lower() if "." in fname else "(none)"
    col2.write(f"**Extension detected:** `.{ext}`")
    exp_ext = st.text_input("Expected file extension (without dot)", value="csv", key="exp_ext")
    if exp_ext:
        if ext == exp_ext.strip().lower():
            st.success(f"✅ Extension `.{ext}` matches expected `.{exp_ext.strip().lower()}`")
        else:
            st.error(f"❌ Extension `.{ext}` does not match expected `.{exp_ext.strip().lower()}`")

    # ── Column spec check ────────────────────────────────────────────────────
    st.markdown("---")
    st.markdown("**Column Count, Order & Names vs. Specification**")
    st.caption("Paste the expected column names from the vendor spec — one per line, in order.")
    spec_cols_input = st.text_area("Expected columns (one per line, in order)", height=150, key="spec_cols")
    if st.button("Compare columns", key="btn_col_spec") and spec_cols_input.strip():
        spec_cols = [c.strip() for c in spec_cols_input.splitlines() if c.strip()]
        actual    = cols

        spec_set   = set(spec_cols)
        actual_set = set(actual)
        missing    = [c for c in spec_cols if c not in actual_set]
        extra      = [c for c in actual if c not in spec_set]
        order_ok   = actual[:len(spec_cols)] == spec_cols if len(actual) >= len(spec_cols) else False

        ma, mb, mc = st.columns(3)
        ma.metric("Expected columns", len(spec_cols))
        mb.metric("Actual columns", len(actual))
        mc.metric("Column count match", "✅ YES" if len(spec_cols) == len(actual) else "❌ NO")

        if missing:
            st.error(f"**Missing from output** ({len(missing)}): `{'`, `'.join(missing)}`")
        if extra:
            st.warning(f"**Extra columns not in spec** ({len(extra)}): `{'`, `'.join(extra)}`")
        if not missing and not extra:
            st.success("✅ All expected columns are present with no extras.")
        st.write(f"**Column order matches spec:** {'✅ YES' if order_ok else '❌ NO — check ordering'}")

        # Side-by-side diff
        max_len = max(len(spec_cols), len(actual))
        diff_rows = []
        for i in range(max_len):
            sc = spec_cols[i] if i < len(spec_cols) else "—"
            ac = actual[i]    if i < len(actual)     else "—"
            diff_rows.append({"#": i+1, "Expected": sc, "Actual": ac,
                               "Match": "✅" if sc == ac else "❌"})
        st.dataframe(pd.DataFrame(diff_rows), use_container_width=True, height=400)

    # ── Reporting period ──────────────────────────────────────────────────────
    st.markdown("---")
    st.markdown("**Reporting Period Validation**")
    st.caption("Confirm the reporting period applied to this output aligns with the agreed cadence.")
    rp_col     = st.selectbox("Date column representing the reporting period", cols, key="rp_col")
    rp_fmt     = st.text_input("Date format", value="%Y-%m-%d", key="rp_fmt")
    rp_exp_min = st.text_input("Expected period start (inclusive)", placeholder="e.g. 2024-01-01", key="rp_exp_min")
    rp_exp_max = st.text_input("Expected period end (inclusive)",   placeholder="e.g. 2024-12-31", key="rp_exp_max")

    if st.button("Validate period", key="btn_rp"):
        try:
            parsed = pd.to_datetime(df[rp_col].astype(str).str.strip(), format=rp_fmt, errors="coerce")
            actual_min = parsed.min()
            actual_max = parsed.max()
            ma, mb = st.columns(2)
            ma.metric("Actual min date in output", str(actual_min.date()) if pd.notna(actual_min) else "N/A")
            mb.metric("Actual max date in output", str(actual_max.date()) if pd.notna(actual_max) else "N/A")

            if rp_exp_min.strip():
                exp_min = pd.Timestamp(rp_exp_min.strip())
                if pd.notna(actual_min) and actual_min.date() == exp_min.date():
                    st.success(f"✅ Min date matches expected start {rp_exp_min}.")
                else:
                    st.error(f"❌ Min date {actual_min.date() if pd.notna(actual_min) else 'N/A'} ≠ expected {rp_exp_min}.")
            if rp_exp_max.strip():
                exp_max = pd.Timestamp(rp_exp_max.strip())
                if pd.notna(actual_max) and actual_max.date() == exp_max.date():
                    st.success(f"✅ Max date matches expected end {rp_exp_max}.")
                else:
                    st.error(f"❌ Max date {actual_max.date() if pd.notna(actual_max) else 'N/A'} ≠ expected {rp_exp_max}.")

            # Distribution of dates to spot gaps
            dist = parsed.dt.to_period("M").astype(str).value_counts().reset_index()
            dist.columns = ["Month", "Count"]
            dist = dist.sort_values("Month")
            st.markdown("**Monthly distribution in output:**")
            st.bar_chart(dist.set_index("Month")["Count"])
        except Exception as e:
            st.error(f"Error: {e}")

    # ── Data type profile ─────────────────────────────────────────────────────
    st.markdown("---")
    st.markdown("**Field Datatype Profile**")
    st.caption(
        "Inspect the inferred data type of each column. "
        "All columns are loaded as strings — this attempts to classify them by their actual content."
    )
    if st.button("Profile datatypes", key="btn_dtype"):
        dtype_rows = []
        for col in cols:
            s      = df[col].dropna().astype(str).str.strip()
            s_nn   = s[s != ""]
            n_tot  = len(df[col])
            n_null = int(df[col].isnull().sum()) + int((df[col].astype(str).str.strip() == "").sum())

            # Try numeric
            num = pd.to_numeric(s_nn, errors="coerce")
            pct_num = num.notna().mean() if len(s_nn) > 0 else 0

            # Try integer subset
            pct_int = (num.dropna() == num.dropna().astype("Int64")).mean() if num.notna().any() else 0

            # Try date (common formats)
            date_parsed = pd.to_datetime(s_nn, errors="coerce", infer_datetime_format=True)
            pct_date = date_parsed.notna().mean() if len(s_nn) > 0 else 0

            max_len = int(s_nn.str.len().max()) if len(s_nn) > 0 else 0

            if pct_num >= 0.95:
                inferred = "Integer" if pct_int >= 0.99 else "Decimal / Float"
            elif pct_date >= 0.90:
                inferred = "Date"
            else:
                inferred = "String / Varchar"

            dtype_rows.append({
                "Column": col,
                "Inferred Type": inferred,
                "Max Length": max_len,
                "Null / Blank": n_null,
                "Null %": round(n_null / n_tot * 100, 1) if n_tot else 0,
                "% Numeric": round(pct_num * 100, 1),
                "% Date-like": round(pct_date * 100, 1),
            })
        st.dataframe(pd.DataFrame(dtype_rows), use_container_width=True, height=500)


# ════════════════════════════════════════════════════════════════════════════
# TAB 2 — Data Completeness
# ════════════════════════════════════════════════════════════════════════════
with tabs[2]:
    st.subheader("Data Completeness")

    # ── Full field population overview ───────────────────────────────────────
    st.markdown("**Full Field Population Overview**")
    st.caption("Confirm no column is entirely empty or entirely null when data is expected.")
    if st.button("Run", key="btn_pop"):
        rows_out = []
        for col in cols:
            s       = df[col]
            null_n  = int(s.isnull().sum())
            blank_n = int((s.astype(str).str.strip() == "").sum())
            empty_n = null_n + blank_n
            filled  = total_rows - empty_n
            n_uniq  = int(s.nunique(dropna=True))
            rows_out.append({
                "Column": col,
                "Filled": filled,
                "Empty": empty_n,
                "Fill %": round(filled / total_rows * 100, 2),
                "Unique Values": n_uniq,
                "⚠️ 100% Null": "YES" if filled == 0 else "",
                "⚠️ Constant": "YES" if n_uniq <= 1 and filled > 0 else "",
            })
        st.session_state["pop_results"] = pd.DataFrame(rows_out).sort_values("Fill %")

    if "pop_results" in st.session_state:
        row = drilldown(st.session_state["pop_results"], "pop",
                        "Click a row to see records where that field is empty.")
        if row is not None:
            col_name   = row["Column"]
            empty_mask = df[col_name].isnull() | (df[col_name].astype(str).str.strip() == "")
            res        = df[empty_mask].reset_index(drop=True)
            if not res.empty:
                st.markdown(f"#### `{col_name}` — {len(res):,} empty rows")
                st.dataframe(res, use_container_width=True)
            else:
                st.success(f"✅ `{col_name}` has no empty rows.")

    # ── Raw vs. output count comparison ─────────────────────────────────────
    st.markdown("---")
    st.markdown("**Raw Source Count vs. Report Output Count**")
    st.caption(
        "Compare the row count in this output against the raw source table count. "
        "Any difference should be fully explainable (filters, joins, deduplication)."
    )
    raw_count = st.number_input("Raw source table row count", min_value=0, value=0, step=1, key="raw_count")
    if raw_count > 0:
        diff     = total_rows - raw_count
        pct_diff = diff / raw_count * 100
        ma, mb, mc = st.columns(3)
        ma.metric("Source count", f"{raw_count:,}")
        mb.metric("Output count", f"{total_rows:,}")
        mc.metric("Difference", f"{diff:+,}", delta=f"{pct_diff:+.2f}%",
                  delta_color="inverse" if abs(pct_diff) > 1 else "normal")
        if diff < 0:
            st.warning(f"⚠️ Output has {abs(diff):,} fewer rows than the source ({abs(pct_diff):.2f}% drop). "
                       "Investigate joins, filters, or deduplication logic.")
        elif diff > 0:
            st.warning(f"⚠️ Output has {diff:,} more rows than the source ({pct_diff:.2f}% gain). "
                       "Check for unintended fan-out from joins.")
        else:
            st.success("✅ Output count matches source count exactly.")

    st.text_area("Notes — document known exclusions and reasons", height=80, key="completeness_notes")

    # ── Expected population filter check ─────────────────────────────────────
    st.markdown("---")
    st.markdown("**Expected Population Filter**")
    st.caption(
        "Verify only the intended population is included. "
        "Select a column and the allowed values — any other values are unexpected."
    )
    pop_col  = st.selectbox("Column to validate population by", cols, key="pop_filter_col")
    pop_vals = st.text_area("Allowed values (one per line)", height=80, key="pop_filter_vals")
    if st.button("Check population", key="btn_pop_filter") and pop_vals.strip():
        allowed  = {v.strip() for v in pop_vals.splitlines() if v.strip()}
        bad_mask = ~df[pop_col].astype(str).str.strip().isin(allowed)
        bad_vals = df.loc[bad_mask, pop_col].value_counts().reset_index(name="Count")
        bad_vals.columns = [pop_col, "Count"]
        st.metric("Rows with unexpected population values", f"{int(bad_mask.sum()):,}")
        if not bad_vals.empty:
            row = drilldown(bad_vals, "pop_filter",
                            "Click a value to see all records with that unexpected population code.")
            if row is not None:
                val  = row[pop_col]
                mask = df[pop_col].astype(str).str.strip() == str(val)
                res  = df[mask].reset_index(drop=True)
                st.markdown(f"#### `{pop_col}` = `{val}` — {len(res):,} rows")
                st.dataframe(res, use_container_width=True)
        else:
            st.success("✅ All rows belong to the expected population.")

    # ── Duplicate records ────────────────────────────────────────────────────
    st.markdown("---")
    st.markdown("**Duplicate Record Count**")
    st.caption("Document duplicates and confirm count is zero, or that any duplicates are expected and explainable.")
    fs_dup_cols = st.multiselect("Columns defining a unique record", cols, key="fs_dup_cols")
    if st.button("Check duplicates", key="btn_fs_dup") and fs_dup_cols:
        dup_mask = df.duplicated(subset=fs_dup_cols, keep=False)
        n_dup    = int(dup_mask.sum())
        st.metric("Duplicate rows", f"{n_dup:,}")
        if n_dup:
            counts = (
                df[fs_dup_cols]
                .value_counts()
                .reset_index(name="count")
                .query("count > 1")
                .reset_index(drop=True)
            )
            st.session_state["dup_counts"]   = counts
            st.session_state["dup_key_cols"] = fs_dup_cols
        else:
            st.success("✅ No duplicate records found.")
            st.session_state.pop("dup_counts", None)

    if "dup_counts" in st.session_state:
        counts   = st.session_state["dup_counts"]
        key_cols = st.session_state["dup_key_cols"]
        st.caption("Click a row to see all records for that key combination.")
        sel = st.dataframe(
            counts, use_container_width=True,
            on_select="rerun", selection_mode="single-row", key="dup_sel_table",
        )
        selected_rows = sel.selection.rows if sel.selection else []
        if selected_rows:
            row  = counts.iloc[selected_rows[0]]
            mask = pd.Series([True] * len(df), index=df.index)
            for col in key_cols:
                mask &= df[col].astype(str) == str(row[col])
            matching = df[mask].reset_index(drop=True)
            st.markdown(f"#### All {len(matching)} duplicate rows for selected key")
            varying  = [c for c in df.columns if c not in key_cols and matching[c].nunique() > 1]
            if varying:
                st.success(f"**Columns that differ** (possible dedup key additions): `{'`, `'.join(varying)}`")
            st.dataframe(matching, use_container_width=True)


# ════════════════════════════════════════════════════════════════════════════
# TAB 3 — Member Identification
# ════════════════════════════════════════════════════════════════════════════
with tabs[3]:
    st.subheader("Member Identification")

    # ── UPID 100% populated ──────────────────────────────────────────────────
    st.markdown("**Member UPID — 100% Populated**")
    st.caption("The member UPID must be populated on every row — zero nulls. Trace any nulls to their source.")
    upid_col = st.selectbox("Member UPID column", cols, key="upid_col")
    if st.button("Check UPID population", key="btn_upid_pop"):
        s       = df[upid_col]
        null_n  = int(s.isnull().sum())
        blank_n = int((s.astype(str).str.strip() == "").sum())
        empty_n = null_n + blank_n
        st.metric("Null / blank UPID rows", f"{empty_n:,}",
                  delta="✅ PASS" if empty_n == 0 else f"❌ FAIL — {empty_n:,} missing")
        if empty_n:
            mask = s.isnull() | (s.astype(str).str.strip() == "")
            st.dataframe(df[mask].reset_index(drop=True), use_container_width=True)
        else:
            st.success("✅ UPID is populated on every row.")

    # ── UPID format validation ────────────────────────────────────────────────
    st.markdown("---")
    st.markdown("**UPID Format Validation**")
    st.caption("Validate that member IDs conform to the vendor-specified format (length, character type, prefix/suffix).")
    upid_fmt_col = st.selectbox("UPID column to validate", cols, key="upid_fmt_col")
    fa, fb, fc_  = st.columns(3)
    upid_exp_len = fa.number_input("Expected exact length (0 = skip)", min_value=0, value=0, key="upid_exp_len")
    upid_regex   = fb.text_input("Regex pattern (leave blank to skip)", placeholder=r"^\d{9}$", key="upid_regex")
    upid_max_len = fc_.number_input("Maximum allowed length (0 = skip)", min_value=0, value=0, key="upid_max_len")

    if st.button("Validate format", key="btn_upid_fmt"):
        s    = df[upid_fmt_col].astype(str).str.strip()
        hits = []

        if upid_exp_len > 0:
            wrong_len = s[(s != "") & (s.str.len() != upid_exp_len)]
            cnt = len(wrong_len)
            hits.append({"Check": f"Length ≠ {upid_exp_len}", "Count": cnt,
                         "_mask": ((s != "") & (s.str.len() != upid_exp_len)).values})

        if upid_max_len > 0:
            over_max = s[s.str.len() > upid_max_len]
            hits.append({"Check": f"Length > {upid_max_len}", "Count": len(over_max),
                         "_mask": (s.str.len() > upid_max_len).values})

        if upid_regex.strip():
            try:
                pattern  = re.compile(upid_regex.strip())
                no_match = s[(s != "") & ~s.str.fullmatch(upid_regex.strip())]
                hits.append({"Check": f"Does not match `{upid_regex.strip()}`", "Count": len(no_match),
                             "_mask": ((s != "") & ~s.str.fullmatch(upid_regex.strip())).values})
            except re.error as e:
                st.error(f"Invalid regex: {e}")

        if hits:
            summary = pd.DataFrame([{"Check": h["Check"], "Count": h["Count"]} for h in hits])
            row = drilldown(summary, "upid_fmt", "Click a check to see the offending rows.")
            if row is not None:
                chosen = next(h for h in hits if h["Check"] == row["Check"])
                res    = df[chosen["_mask"]].reset_index(drop=True)
                st.markdown(f"#### {chosen['Check']} — {len(res):,} rows")
                st.dataframe(res, use_container_width=True)
            if all(h["Count"] == 0 for h in hits):
                st.success("✅ All UPID values pass format validation.")
        else:
            st.info("Configure at least one format check above and click Validate.")

    # ── UPID → one member only ────────────────────────────────────────────────
    st.markdown("---")
    st.markdown("**UPID → Exactly One Member**")
    st.caption("Each UPID should map to exactly one distinct member. Flag duplicate IDs with mismatched demographics.")
    upid_id_cols  = st.multiselect("UPID / member ID column(s)", cols, key="upid_id_cols")
    upid_bio_cols = st.multiselect("Demographic columns (Name, DOB, Sex…)", cols, key="upid_bio_cols")
    if st.button("Check", key="btn_upid_uniq") and upid_id_cols and upid_bio_cols:
        tmp = df.copy()
        for c in upid_id_cols + upid_bio_cols:
            tmp[c] = tmp[c].astype(str).str.strip().str.upper()
        tmp["_ID"]   = list(zip(*(tmp[c] for c in upid_id_cols)))
        tmp["_DEMO"] = list(zip(*(tmp[c] for c in upid_bio_cols)))
        check = tmp.groupby("_ID")["_DEMO"].nunique().reset_index(name="distinct_identities")
        bad   = check[check["distinct_identities"] > 1]
        st.metric("UPIDs linked to multiple distinct identities", f"{len(bad):,}")
        if not bad.empty:
            summary_rows = []
            for id_val in bad["_ID"].tolist():
                n_ids = int(bad.loc[bad["_ID"] == id_val, "distinct_identities"].iloc[0])
                label = " | ".join(str(v) for v in id_val) if isinstance(id_val, tuple) else str(id_val)
                summary_rows.append({"UPID": label, "Distinct Identities": n_ids, "_ID": id_val})
            summary_df = pd.DataFrame(summary_rows)
            st.session_state["upid_summary"]  = summary_df
            st.session_state["upid_tmp"]      = tmp
            st.session_state["upid_id_cols"]  = upid_id_cols
            st.session_state["upid_bio_cols"] = upid_bio_cols
        else:
            st.success("✅ All UPIDs map to exactly one member.")
            st.session_state.pop("upid_summary", None)

    if "upid_summary" in st.session_state:
        display_summary = st.session_state["upid_summary"][["UPID", "Distinct Identities"]]
        row = drilldown(display_summary, "upid_uniq",
                        "Click a UPID to see all records with conflicting demographics.")
        if row is not None:
            chosen_id = st.session_state["upid_summary"].iloc[
                display_summary.index[display_summary["UPID"] == row["UPID"]][0]
            ]["_ID"]
            tmp2   = st.session_state["upid_tmp"]
            mask   = tmp2["_ID"] == chosen_id
            res    = df[mask.values].reset_index(drop=True)
            st.markdown(f"#### UPID `{row['UPID']}` — {len(res):,} rows ({row['Distinct Identities']} distinct identities)")
            st.dataframe(res, use_container_width=True)

    # ── Cross-report identifier linkage ──────────────────────────────────────
    st.markdown("---")
    st.markdown("**Cross-Report Identifier Linkage**")
    st.caption(
        "If the vendor receives multiple report types (e.g., claims + eligibility), "
        "upload a second report and confirm the shared member identifier links records correctly."
    )
    uploaded2 = st.file_uploader("Upload second report (CSV or TXT)", type=["csv", "txt"], key="upload2")
    if uploaded2 is not None:
        try:
            raw2  = uploaded2.read()
            df2   = load_file(raw2, DELIM[delim_label], skip_space, no_quote)
            st.success(f"Second report: **{df2.shape[0]:,} rows × {df2.shape[1]} columns**")
            cols2 = df2.columns.tolist()

            link_col1 = st.selectbox("Shared ID column in Report 1", cols,  key="link_col1")
            link_col2 = st.selectbox("Shared ID column in Report 2", cols2, key="link_col2")
            if st.button("Check linkage", key="btn_crossreport"):
                ids1 = set(df[link_col1].astype(str).str.strip().dropna())
                ids2 = set(df2[link_col2].astype(str).str.strip().dropna())
                only_in_1 = ids1 - ids2
                only_in_2 = ids2 - ids1
                in_both   = ids1 & ids2
                ma, mb, mc = st.columns(3)
                ma.metric("In both reports", f"{len(in_both):,}")
                mb.metric("Only in Report 1", f"{len(only_in_1):,}")
                mc.metric("Only in Report 2", f"{len(only_in_2):,}")
                if only_in_1:
                    st.warning(f"⚠️ {len(only_in_1):,} IDs in Report 1 have no match in Report 2.")
                if only_in_2:
                    st.warning(f"⚠️ {len(only_in_2):,} IDs in Report 2 have no match in Report 1.")
                if not only_in_1 and not only_in_2:
                    st.success("✅ All shared IDs link correctly between both reports.")

                if only_in_1:
                    with st.expander("Report 1 rows with unmatched IDs (sample 50)"):
                        res = df[df[link_col1].astype(str).str.strip().isin(only_in_1)].head(50)
                        st.dataframe(res, use_container_width=True)
        except Exception as e:
            st.error(f"Error loading second report: {e}")


# ════════════════════════════════════════════════════════════════════════════
# TAB 4 — Data Mapping Validation
# ════════════════════════════════════════════════════════════════════════════
with tabs[4]:
    st.subheader("Data Mapping Validation")

    # ── Plan identifier / fallback logic ─────────────────────────────────────
    st.markdown("**Plan Identifier Fallback Logic**")
    st.caption(
        "Verify the most granular plan identifier fields are being pulled from source data. "
        "Check that fallback logic works (e.g., use plan ID as primary, plan codes 1–6 as secondary)."
    )
    plan_primary_col  = st.selectbox("Primary plan identifier column", cols, key="plan_primary_col")
    plan_fallback_cols = st.multiselect("Fallback plan columns (in priority order)", cols, key="plan_fallback_cols")
    if st.button("Analyze fallback coverage", key="btn_plan_fallback"):
        tmp = df.copy()
        tmp["_PRI"] = tmp[plan_primary_col].astype(str).str.strip()
        primary_null = tmp["_PRI"].isin(["", "nan", "None", "NULL"])
        st.metric("Primary column populated", f"{int((~primary_null).sum()):,} / {total_rows:,}")

        if plan_fallback_cols:
            fallback_coverage = []
            remaining = primary_null.copy()
            for fb_col in plan_fallback_cols:
                tmp["_FB"] = tmp[fb_col].astype(str).str.strip()
                fb_null    = tmp["_FB"].isin(["", "nan", "None", "NULL"])
                covered_here = remaining & ~fb_null
                fallback_coverage.append({
                    "Fallback Column": fb_col,
                    "Covers (rows filled from this fallback)": int(covered_here.sum()),
                })
                remaining = remaining & fb_null  # still null after this fallback
            fallback_coverage.append({"Fallback Column": "Still null after all fallbacks", "Covers": int(remaining.sum())})
            st.dataframe(pd.DataFrame(fallback_coverage), use_container_width=True)

        dist = df[plan_primary_col].value_counts(dropna=False).reset_index()
        dist.columns = ["Value", "Count"]
        dist["%"] = (dist["Count"] / total_rows * 100).round(2)
        row = drilldown(dist, "plan_dist", "Click a plan value to see all records.")
        if row is not None:
            val  = row["Value"]
            mask = df[plan_primary_col].astype(str) == str(val) if pd.notna(val) else df[plan_primary_col].isnull()
            res  = df[mask].reset_index(drop=True)
            st.markdown(f"#### Plan `{val}` — {len(res):,} rows")
            st.dataframe(res, use_container_width=True)

    # ── Carrier-specific mapping / enumerated values ──────────────────────────
    st.markdown("---")
    st.markdown("**Carrier-Specific Mapping — Enumerated Value Check**")
    st.caption(
        "Validate that carrier-specific mapping logic produces only the vendor's required enumerated values. "
        "No raw source codes or freeform strings should appear in categorical output fields."
    )
    map_col  = st.selectbox("Categorical field to validate", cols, key="map_col")
    map_vals = st.text_area("Allowed output values per vendor spec (one per line)", height=100, key="map_vals")
    if st.button("Run", key="btn_map_vals") and map_vals.strip():
        allowed    = {v.strip() for v in map_vals.splitlines() if v.strip()}
        actual_all = set(df[map_col].astype(str).str.strip().unique())
        unexpected = actual_all - allowed
        st.metric("Unexpected / unmapped values", len(unexpected))
        if unexpected:
            bad_mask = df[map_col].astype(str).str.strip().isin(unexpected)
            ev_df    = df.loc[bad_mask, [map_col]].value_counts().reset_index(name="Count")
            row = drilldown(ev_df, "map_ev", "Click a value to see all records with that unmapped code.")
            if row is not None:
                val  = row[map_col]
                mask = df[map_col].astype(str).str.strip() == str(val)
                res  = df[mask].reset_index(drop=True)
                st.markdown(f"#### `{map_col}` = `{val}` — {len(res):,} rows")
                st.dataframe(res, use_container_width=True)
        else:
            st.success(f"✅ All values in `{map_col}` are in the allowed set.")

    # ── Hardcoded / vendor-specific transformations ───────────────────────────
    st.markdown("---")
    st.markdown("**Hardcoded / Vendor-Specific Transformations**")
    st.caption(
        "Verify vendor-specific transformations (e.g., constant values, derived fields). "
        "Select a column and confirm it always equals the expected value."
    )
    hc_col = st.selectbox("Column to inspect", cols, key="hc_col")
    hc_exp = st.text_input("Expected constant value (leave blank to just see distribution)", key="hc_exp")
    if st.button("Check", key="btn_hc"):
        dist = df[hc_col].value_counts(dropna=False).reset_index()
        dist.columns = ["Value", "Count"]
        dist["%"] = (dist["Count"] / total_rows * 100).round(2)
        st.dataframe(dist, use_container_width=True)
        if hc_exp.strip():
            matches = (df[hc_col].astype(str).str.strip() == hc_exp.strip()).sum()
            if matches == total_rows:
                st.success(f"✅ `{hc_col}` is always `{hc_exp.strip()}` — transformation correct.")
            else:
                st.error(f"❌ Only {matches:,} of {total_rows:,} rows have `{hc_col}` = `{hc_exp.strip()}`.")


# ════════════════════════════════════════════════════════════════════════════
# TAB 5 — Null & Allowed Values
# ════════════════════════════════════════════════════════════════════════════
with tabs[5]:
    st.subheader("Null & Allowed Values")

    # ── Null count summary ────────────────────────────────────────────────────
    st.markdown("**Null Count & Rate — All Fields**")
    st.caption(
        "Run null counts on all fields. For fields with unexpectedly high null rates, "
        "trace the root cause: missing carrier data, incorrect mapping, dropped join, query logic error."
    )
    if st.button("Run null scan", key="btn_null_scan"):
        rows_out = []
        for col in cols:
            s       = df[col]
            null_n  = int(s.isnull().sum())
            blank_n = int((s.astype(str).str.strip() == "").sum())
            null_s  = int((s.astype(str).str.strip().str.lower() == "null").sum())
            empty_n = null_n + blank_n
            rows_out.append({
                "Column": col,
                "NaN": null_n,
                "Blank": blank_n,
                '"null" string': null_s,
                "Total Empty": empty_n,
                "Null %": round(empty_n / total_rows * 100, 2),
                "⚠️ 100% Null": "YES" if empty_n == total_rows else "",
            })
        null_df = pd.DataFrame(rows_out).sort_values("Null %", ascending=False)
        st.session_state["null_summary"] = null_df

    if "null_summary" in st.session_state:
        row = drilldown(st.session_state["null_summary"], "null_scan",
                        "Click a column to see records where that field is null/blank.")
        if row is not None:
            col_name   = row["Column"]
            empty_mask = df[col_name].isnull() | (df[col_name].astype(str).str.strip() == "")
            res        = df[empty_mask].reset_index(drop=True)
            if not res.empty:
                st.markdown(f"#### `{col_name}` — {len(res):,} null/blank rows")
                st.dataframe(res, use_container_width=True)
            else:
                st.success(f"✅ `{col_name}` has no null/blank rows.")

    # ── Conditional population check ─────────────────────────────────────────
    st.markdown("---")
    st.markdown("**Conditional Field Population**")
    st.caption(
        "Fields dependent on other fields should only be populated when appropriate. "
        "Example: Diagnosis Type Code should only be populated when a Diagnosis Code is present."
    )
    cond_dep_col    = st.selectbox("Dependent field (should only populate when condition is met)", cols, key="cond_dep_col")
    cond_parent_col = st.selectbox("Parent / trigger field (must be non-null for dependent to populate)", cols, key="cond_parent_col")
    if st.button("Check", key="btn_cond_pop"):
        tmp = df.copy()
        parent_empty = tmp[cond_parent_col].isnull() | (tmp[cond_parent_col].astype(str).str.strip() == "")
        dep_filled   = ~(tmp[cond_dep_col].isnull()  | (tmp[cond_dep_col].astype(str).str.strip()   == ""))
        violation    = parent_empty & dep_filled

        ma, mb = st.columns(2)
        ma.metric(f"Rows where `{cond_parent_col}` is null", f"{int(parent_empty.sum()):,}")
        mb.metric(f"Of those, `{cond_dep_col}` is populated (violation)", f"{int(violation.sum()):,}",
                  delta="✅ None" if violation.sum() == 0 else f"❌ {int(violation.sum()):,}",
                  delta_color="normal" if violation.sum() == 0 else "inverse")
        if violation.any():
            st.warning(f"⚠️ `{cond_dep_col}` is populated on {int(violation.sum()):,} rows where `{cond_parent_col}` is null.")
            st.session_state["cond_null_hits"] = df[violation].reset_index(drop=True)
        else:
            st.success(f"✅ `{cond_dep_col}` only populates when `{cond_parent_col}` is present.")
            st.session_state.pop("cond_null_hits", None)

    if "cond_null_hits" in st.session_state:
        with st.expander("Show violation records"):
            st.dataframe(st.session_state["cond_null_hits"], use_container_width=True)

    # ── Null-where-expected check ─────────────────────────────────────────────
    st.markdown("---")
    st.markdown("**Null-Where-Expected Check**")
    st.caption(
        "Values defined as null in the vendor layout should be null — not empty string, "
        "not '0', not 'N/A'. Select a column and specify what the empty-state value should be."
    )
    nwe_col      = st.selectbox("Column to inspect", cols, key="nwe_col")
    nwe_expected = st.radio("What should empty state look like for this field?",
                            ["NULL / NaN", "Empty string (\"\")", "Zero (0)", "Other"],
                            key="nwe_expected")
    nwe_other    = st.text_input("Other expected empty value", key="nwe_other") if nwe_expected == "Other" else ""
    if st.button("Check", key="btn_nwe"):
        s = df[nwe_col]
        s_str = s.astype(str).str.strip()
        null_n  = int(s.isnull().sum())
        blank_n = int((s_str == "").sum())
        zero_n  = int((s_str == "0").sum())
        na_n    = int((s_str.str.lower().isin(["n/a", "na", "null", "none"])).sum())
        other_n = int((s_str == nwe_other.strip()).sum()) if nwe_other.strip() else 0

        st.write(f"**NaN**: {null_n:,} | **Blank string**: {blank_n:,} | **'0'**: {zero_n:,} | **N/A-like string**: {na_n:,}")
        if nwe_expected == "NULL / NaN" and (blank_n or zero_n):
            st.warning(f"⚠️ Found {blank_n:,} blank strings and {zero_n:,} zeros — expected NULLs only.")
        elif nwe_expected == 'Empty string ("")' and null_n:
            st.warning(f"⚠️ Found {null_n:,} NaN values — expected empty strings.")
        elif nwe_expected == "Zero (0)" and (null_n or blank_n):
            st.warning(f"⚠️ Found {null_n:,} NaN + {blank_n:,} blank — expected zeros.")
        else:
            st.success("✅ Empty-state values appear consistent with expectation.")

    # ── Allowed values scan ───────────────────────────────────────────────────
    st.markdown("---")
    st.markdown("**Allowed Values Check — All Categorical Fields**")
    st.caption(
        "For every categorical field, confirm all values in the output are members of the agreed "
        "allowed-value list — no raw source codes, no freeform strings."
    )
    ev_col  = st.selectbox("Column to validate", cols, key="ev_col")
    ev_vals = st.text_area("Allowed values (one per line)", key="ev_vals", height=100)
    if st.button("Run", key="btn_ev") and ev_vals.strip():
        allowed    = {v.strip() for v in ev_vals.splitlines() if v.strip()}
        actual     = set(df[ev_col].dropna().astype(str).str.strip().unique())
        unexpected = actual - allowed
        st.metric("Unexpected values", len(unexpected))
        if unexpected:
            bad_mask = df[ev_col].astype(str).str.strip().isin(unexpected)
            ev_df    = df.loc[bad_mask, [ev_col]].value_counts().reset_index(name="Count")
            st.session_state["ev_hits"]      = ev_df
            st.session_state["ev_col_saved"] = ev_col
        else:
            st.success(f"✅ All values in `{ev_col}` match the allowed set.")
            st.session_state.pop("ev_hits", None)

    if "ev_hits" in st.session_state:
        row = drilldown(st.session_state["ev_hits"], "ev",
                        "Click a value to see all records with that unexpected value.")
        if row is not None:
            ec   = st.session_state["ev_col_saved"]
            val  = row[ec]
            mask = df[ec].astype(str).str.strip() == str(val)
            res  = df[mask].reset_index(drop=True)
            st.markdown(f"#### `{ec}` = `{val}` — {len(res):,} rows")
            st.dataframe(res, use_container_width=True)


# ════════════════════════════════════════════════════════════════════════════
# TAB 6 — Formatting & Logic
# ════════════════════════════════════════════════════════════════════════════
with tabs[6]:
    st.subheader("Data Formatting & Logic")

    # ── Field length validation ───────────────────────────────────────────────
    st.markdown("**Field Length / Max Length Validation**")
    st.caption(
        "Verify each field does not exceed its defined maximum length. "
        "Varchar fields must not exceed defined length; BIGINT ceiling for numeric IDs."
    )
    len_col     = st.selectbox("Column to check", cols, key="len_col")
    len_max     = st.number_input("Max allowed length", min_value=1, value=50, key="len_max")
    len_exp_len = st.number_input("Expected exact length (0 = skip)", min_value=0, value=0, key="len_exp_len")

    if st.button("Check lengths", key="btn_len"):
        s = df[len_col].astype(str).str.strip()
        s_nn = s[s != ""]

        by_len = s_nn.str.len().value_counts().reset_index()
        by_len.columns = ["Length", "Count"]
        by_len["%"] = (by_len["Count"] / total_rows * 100).round(2)
        by_len = by_len.sort_values("Length")

        over_max = s_nn[s_nn.str.len() > len_max]
        wrong_len = s_nn[s_nn.str.len() != len_exp_len] if len_exp_len > 0 else pd.Series(dtype=str)

        ma, mb, mc = st.columns(3)
        ma.metric("Max length in data", f"{int(s_nn.str.len().max()) if len(s_nn) else 0}")
        mb.metric(f"Over max ({len_max})", f"{len(over_max):,}",
                  delta="✅ None" if len(over_max) == 0 else f"❌ {len(over_max):,}",
                  delta_color="normal" if len(over_max) == 0 else "inverse")
        if len_exp_len > 0:
            mc.metric(f"Wrong length (≠ {len_exp_len})", f"{len(wrong_len):,}",
                      delta="✅ None" if len(wrong_len) == 0 else f"❌ {len(wrong_len):,}",
                      delta_color="normal" if len(wrong_len) == 0 else "inverse")

        st.session_state["len_summary"]   = by_len
        st.session_state["len_col_saved"] = len_col
        st.session_state["len_max_val"]   = len_max
        st.session_state["len_exp_len"]   = len_exp_len

    if "len_summary" in st.session_state:
        row = drilldown(st.session_state["len_summary"], "len",
                        "Click a length bucket to see all records with that field length.")
        if row is not None:
            nc   = st.session_state["len_col_saved"]
            tlen = int(row["Length"])
            mask = df[nc].astype(str).str.strip().str.len() == tlen
            res  = df[mask].reset_index(drop=True)
            st.markdown(f"#### `{nc}` length = {tlen} — {len(res):,} rows")
            st.dataframe(res, use_container_width=True)

    # ── Date format validation ────────────────────────────────────────────────
    st.markdown("---")
    st.markdown("**Date Field Format Validation**")
    st.caption(
        "Confirm all date fields follow the vendor-specified format consistently "
        "(e.g., YYYYMMDD, YYYYMM, YYYY-MM-DD). "
        "Also flags truncation when dates are cast to varchar."
    )
    auto_date_cols = [c for c in cols if any(x in c.lower() for x in ["date", "dob", "doh", "dot", "dt"])]
    date_cols_tab  = st.multiselect("Date columns to analyze", cols, default=auto_date_cols, key="dv_cols")
    date_fmt_tab   = st.text_input("Expected date format", value="%Y-%m-%d", key="dv_fmt",
                                   help="e.g. %Y-%m-%d | %m/%d/%Y | %Y%m%d | %Y%m")
    sys_defaults   = st.text_input(
        "Sentinel / system-default dates to flag (comma-separated)",
        value="1753-01-01,9999-12-31,1900-01-01,0001-01-01,19000101,99991231",
        key="dv_defaults",
    )
    if st.button("Run date analysis", key="btn_dv") and date_cols_tab:
        sentinel_vals = {v.strip() for v in sys_defaults.split(",") if v.strip()}
        today = pd.Timestamp(date.today())
        for col in date_cols_tab:
            st.markdown(f"**{col}**")
            raw_s     = df[col].astype(str).str.strip()
            parsed    = pd.to_datetime(raw_s, format=date_fmt_tab, errors="coerce")
            blank_n   = int((raw_s == "").sum()) + int(df[col].isnull().sum())
            parse_err = int(parsed.isnull().sum()) - blank_n
            future_n  = int((parsed > today).sum())
            default_n = int(raw_s.isin(sentinel_vals).sum())
            # Check format length consistency (truncation)
            s_nn     = raw_s[raw_s != ""]
            exp_fmtlen = len(date.today().strftime(date_fmt_tab)) if "%" in date_fmt_tab else 0
            trunc_n  = int((s_nn.str.len() < exp_fmtlen).sum()) if exp_fmtlen > 0 else 0
            ma, mb, mc, md, me = st.columns(5)
            ma.metric("Blank", f"{blank_n:,}")
            mb.metric("Parse Errors", f"{parse_err:,}")
            mc.metric("Future Dates", f"{future_n:,}")
            md.metric("Sentinel Defaults", f"{default_n:,}")
            me.metric("Possibly Truncated", f"{trunc_n:,}")
            if parse_err:
                with st.expander(f"Parse error rows — {col}"):
                    st.dataframe(df[parsed.isnull() & (raw_s != "")][[col]].head(20), use_container_width=True)
            if future_n:
                with st.expander(f"Future date rows — {col}"):
                    st.dataframe(df[parsed > today][[col]].head(20), use_container_width=True)
            if default_n:
                with st.expander(f"Sentinel date rows — {col}"):
                    st.dataframe(df[raw_s.isin(sentinel_vals)][[col]].head(20), use_container_width=True)

    # ── Date order check ─────────────────────────────────────────────────────
    st.markdown("---")
    st.markdown("**Date Order Check** — Flag rows where an earlier date comes after a later date")
    n_ord = int(st.number_input("Number of comparisons", 0, 8, 2, key="dv_n_ord"))
    order_comps = []
    if date_cols_tab:
        for i in range(n_ord):
            ca, cb = st.columns(2)
            a = ca.selectbox(f"Earlier date [{i+1}]", date_cols_tab, key=f"dv_oa_{i}")
            b = cb.selectbox(f"Later date [{i+1}]",   date_cols_tab,
                             index=min(1, len(date_cols_tab)-1), key=f"dv_ob_{i}")
            order_comps.append((a, b))
    if st.button("Run order check", key="btn_dv_ord") and date_cols_tab and order_comps:
        tmp = df.copy()
        for col in date_cols_tab:
            tmp[col] = pd.to_datetime(tmp[col].astype(str).str.strip(), format=date_fmt_tab, errors="coerce")
        comp_results = []
        for a, b in order_comps:
            if a != b:
                issue = (tmp[a] > tmp[b]).fillna(False)
                comp_results.append({"Earlier (A)": a, "Later (B)": b,
                                     "Label": f"{a} > {b}",
                                     "Rows": int(issue.sum()),
                                     "_mask": issue.values})
        st.session_state["dv_ord_results"]   = comp_results
        st.session_state["dv_ord_date_cols"] = date_cols_tab

    if "dv_ord_results" in st.session_state:
        comp_results = st.session_state["dv_ord_results"]
        if not any(r["Rows"] for r in comp_results):
            st.success("✅ No date order violations found.")
        else:
            summary = pd.DataFrame([{"Comparison": r["Label"], "Rows with Violation": r["Rows"]}
                                     for r in comp_results])
            row = drilldown(summary, "dv_ord", "Click a comparison to see the violating rows.")
            if row is not None:
                chosen = next(r for r in comp_results if r["Label"] == row["Comparison"])
                res    = df[chosen["_mask"]].reset_index(drop=True)
                disp_cols = [c for c in st.session_state["dv_ord_date_cols"] if c in res.columns]
                st.markdown(f"#### `{chosen['Label']}` — {len(res):,} rows")
                st.dataframe(res[disp_cols + [c for c in res.columns if c not in disp_cols]],
                             use_container_width=True)

    # ── Global / non-US record check ─────────────────────────────────────────
    st.markdown("---")
    st.markdown("**Global / Non-US Record Check**")
    st.caption("Confirm that global / non-US records are excluded if out of scope for this report.")
    geo_col = st.selectbox("Country / State / Address column", cols, key="geo_col")
    us_vals = st.text_input(
        "US indicator values (comma-separated, case-insensitive)",
        value="US,USA,United States,United States of America",
        key="us_vals",
    )
    if st.button("Check", key="btn_geo"):
        us_set = {v.strip().lower() for v in us_vals.split(",") if v.strip()}
        s      = df[geo_col].astype(str).str.strip()
        is_us  = s.str.lower().isin(us_set)
        is_non_us = ~is_us & (s != "") & ~df[geo_col].isnull()
        dist = df[geo_col].value_counts(dropna=False).reset_index()
        dist.columns = ["Value", "Count"]
        dist["%"] = (dist["Count"] / total_rows * 100).round(2)
        ma, mb = st.columns(2)
        ma.metric("US records", f"{int(is_us.sum()):,}")
        mb.metric("Non-US records", f"{int(is_non_us.sum()):,}",
                  delta="⚠️ Review" if is_non_us.any() else "✅ None",
                  delta_color="inverse" if is_non_us.any() else "normal")
        row = drilldown(dist, "geo", "Click a value to see all records for that country/state.")
        if row is not None:
            val  = row["Value"]
            mask = df[geo_col].astype(str) == str(val) if pd.notna(val) else df[geo_col].isnull()
            res  = df[mask].reset_index(drop=True)
            st.markdown(f"#### `{geo_col}` = `{val}` — {len(res):,} rows")
            st.dataframe(res, use_container_width=True)


# ════════════════════════════════════════════════════════════════════════════
# TAB 7 — Sanity Checks
# ════════════════════════════════════════════════════════════════════════════
with tabs[7]:
    st.subheader("Sanity Checks")

    # ── 1. Financial reconciliation ───────────────────────────────────────────
    st.markdown("**1. Financial Reconciliation — Plan Paid Amount**")
    st.caption(
        "Reconcile the total plan paid amount in the output against the source / canonical data. "
        "Document and investigate any variance."
    )
    paid_col      = st.selectbox("Plan paid column in output", cols, key="paid_col")
    source_total  = st.number_input("Expected total from source ($)", min_value=0.0, value=0.0,
                                    format="%.2f", key="source_total")
    recon_tol_pct = st.number_input("Acceptable variance % (e.g. 0.01 = 0.01%)", min_value=0.0,
                                    value=0.01, format="%.4f", key="recon_tol_pct")
    if st.button("Reconcile", key="btn_recon"):
        paid_num     = pd.to_numeric(df[paid_col], errors="coerce")
        output_total = paid_num.sum()
        diff         = output_total - source_total
        pct_diff     = (diff / source_total * 100) if source_total != 0 else float("nan")
        ma, mb, mc   = st.columns(3)
        ma.metric("Source total", f"${source_total:,.2f}")
        mb.metric("Output total", f"${output_total:,.2f}")
        mc.metric("Variance", f"${diff:+,.2f}", delta=f"{pct_diff:+.4f}%" if source_total else "N/A",
                  delta_color="inverse" if source_total and abs(pct_diff) > recon_tol_pct else "normal")
        if source_total and abs(pct_diff) > recon_tol_pct:
            st.error(f"❌ Variance of {pct_diff:+.4f}% exceeds tolerance of {recon_tol_pct}%. Investigate.")
        elif source_total:
            st.success(f"✅ Variance of {pct_diff:+.4f}% is within the {recon_tol_pct}% tolerance.")
        st.session_state["fin_recon_result"] = {"source": source_total, "output": output_total, "diff": diff}

    # ── 2. DOB plausibility ───────────────────────────────────────────────────
    st.markdown("---")
    st.markdown("**2. DOB Plausibility Check**")
    st.caption(
        "Validate DOB values are plausible. Flag system-default or known-limitation DOB patterns "
        "(e.g., YOB-01-01 where only year of birth is known)."
    )
    dob_col    = st.selectbox("Date of Birth column", cols, key="dob_col")
    dob_fmt    = st.text_input("DOB format", value="%Y-%m-%d", key="dob_fmt")
    dob_kw_pat = st.text_input(
        "Flag DOB patterns where month/day are defaults (regex)",
        value=r"-01-01$", key="dob_kw_pat",
        help="e.g. -01-01$ flags dates where only year of birth is known",
    )
    max_age_s = st.number_input("Flag ages older than (years)", min_value=90, max_value=130, value=110, key="dob_max_age")
    if st.button("Run DOB check", key="btn_dob"):
        try:
            tmp        = df.copy()
            raw_s      = tmp[dob_col].astype(str).str.strip()
            parsed     = pd.to_datetime(raw_s, format=dob_fmt, errors="coerce")
            today      = pd.Timestamp(date.today())
            age        = ((today - parsed).dt.days / 365.25)
            parse_err  = int(parsed.isnull().sum()) - int(raw_s.isin(["", "nan"]).sum())
            future_dob = int((parsed > today).sum())
            neg_age    = int((age < 0).sum())
            old_age    = int((age > max_age_s).sum())
            default_pat = int(raw_s.str.contains(dob_kw_pat, na=False).sum()) if dob_kw_pat.strip() else 0

            ma, mb, mc, md, me = st.columns(5)
            ma.metric("Parse errors",           f"{parse_err:,}")
            mb.metric("Future DOB",             f"{future_dob:,}")
            mc.metric(f"Age > {max_age_s}",     f"{old_age:,}")
            md.metric("Negative age",           f"{neg_age:,}")
            me.metric("Default pattern match",  f"{default_pat:,}")

            hits = []
            if future_dob:
                hits.append({"Issue": "Future DOB",                            "Count": future_dob,  "_mask": (parsed > today).values})
            if old_age:
                hits.append({"Issue": f"Age > {max_age_s}",                   "Count": old_age,     "_mask": (age > max_age_s).values})
            if default_pat:
                hits.append({"Issue": "Default date pattern (e.g. YOB-01-01)", "Count": default_pat,
                             "_mask": raw_s.str.contains(dob_kw_pat, na=False).values})
            if hits:
                st.session_state["dob_hits"]   = hits
                st.session_state["dob_summary"] = pd.DataFrame([{"Issue": h["Issue"], "Count": h["Count"]} for h in hits])
            else:
                st.success("✅ No DOB issues found.")
                st.session_state.pop("dob_hits",   None)
                st.session_state.pop("dob_summary", None)
        except Exception as e:
            st.error(f"Error: {e}")

    if "dob_summary" in st.session_state:
        row = drilldown(st.session_state["dob_summary"], "dob", "Click an issue to see the flagged records.")
        if row is not None:
            chosen = next(h for h in st.session_state["dob_hits"] if h["Issue"] == row["Issue"])
            res    = df[chosen["_mask"]].reset_index(drop=True)
            st.markdown(f"#### {chosen['Issue']} — {len(res):,} rows")
            st.dataframe(res, use_container_width=True)

    # ── 3. Demographic logic ──────────────────────────────────────────────────
    st.markdown("---")
    st.markdown("**3. Demographic Logic Sanity Check**")
    st.caption(
        "Validate that demographic field combinations are logically consistent. "
        "Examples: toddlers are not coded as employees; dependents over 26 are not coded as children."
    )
    demo_dob_col  = st.selectbox("Date of Birth column",              cols, key="demo_dob_col")
    demo_rel_col  = st.selectbox("Relationship / role column",        cols, key="demo_rel_col")
    demo_dob_fmt  = st.text_input("DOB format", value="%Y-%m-%d",         key="demo_dob_fmt")
    demo_emp_kw   = st.text_input("Employee codes (comma-separated)", value="EE,employee,self,00,E,18", key="demo_emp_kw")
    demo_child_kw = st.text_input("Child / dependent codes (comma-separated)", value="child,02,03,C,D,dependent", key="demo_child_kw")
    demo_min_age  = st.number_input("Min age to be coded employee",   min_value=14, max_value=25, value=16, key="demo_min_age")
    demo_child_max = st.number_input("Max age for child/dependent code", min_value=18, max_value=30, value=26, key="demo_child_max")

    if st.button("Run", key="btn_demo_sanity"):
        try:
            tmp = df.copy()
            tmp["_DOB"] = pd.to_datetime(tmp[demo_dob_col].astype(str).str.strip(),
                                         format=demo_dob_fmt, errors="coerce")
            tmp["_AGE"] = ((pd.Timestamp(date.today()) - tmp["_DOB"]).dt.days / 365.25)
            emp_kws   = {k.strip().lower() for k in demo_emp_kw.split(",")   if k.strip()}
            child_kws = {k.strip().lower() for k in demo_child_kw.split(",") if k.strip()}
            tmp["_REL"] = tmp[demo_rel_col].astype(str).str.strip().str.lower()
            is_emp      = tmp["_REL"].isin(emp_kws)
            is_child    = tmp["_REL"].isin(child_kws)
            minor_emp   = is_emp   & (tmp["_AGE"] < demo_min_age)   & tmp["_AGE"].notna()
            old_child   = is_child & (tmp["_AGE"] > demo_child_max) & tmp["_AGE"].notna()
            hits = []
            if minor_emp.any():
                hits.append({"Issue": f"Age < {demo_min_age} coded as employee",       "Count": int(minor_emp.sum()), "_mask": minor_emp.values})
            if old_child.any():
                hits.append({"Issue": f"Age > {demo_child_max} coded as child/dependent", "Count": int(old_child.sum()), "_mask": old_child.values})
            if hits:
                st.session_state["demo_sanity_hits"]    = hits
                st.session_state["demo_sanity_summary"] = pd.DataFrame([{"Issue": h["Issue"], "Count": h["Count"]} for h in hits])
            else:
                st.success("✅ No demographic logic issues found.")
                st.session_state.pop("demo_sanity_hits",    None)
                st.session_state.pop("demo_sanity_summary", None)
        except Exception as e:
            st.error(f"Error: {e}")

    if "demo_sanity_summary" in st.session_state:
        row = drilldown(st.session_state["demo_sanity_summary"], "demo_sanity", "Click an issue to see the flagged records.")
        if row is not None:
            chosen = next(h for h in st.session_state["demo_sanity_hits"] if h["Issue"] == row["Issue"])
            res    = df[chosen["_mask"]].reset_index(drop=True)
            st.markdown(f"#### {chosen['Issue']} — {len(res):,} rows")
            st.dataframe(res, use_container_width=True)

    # ── 4. Vendor acceptance criteria comparison ──────────────────────────────
    st.markdown("---")
    st.markdown("**4. Vendor Acceptance Criteria Comparison**")
    st.caption(
        "Confirm the output has been compared against vendor acceptance criteria, "
        "a vendor-provided sample output, or a prior approved extract where available. "
        "Document findings below."
    )
    st.text_area(
        "Comparison notes — describe what was compared, any differences found, and disposition",
        height=100, key="vendor_compare_notes",
        placeholder="e.g. Compared against vendor sample file dated 2024-01-15. "
                    "Row counts match. Field X differs in format — confirmed acceptable per email from vendor on 2024-02-01.",
    )

    # ── 5. Filter boundary validation ─────────────────────────────────────────
    st.markdown("---")
    st.markdown("**5. Filter Boundary Validation**")
    st.caption(
        "For each filter applied in the transform (date range, eligibility status, plan, group, etc.), "
        "confirm: (1) min and max values match the intended boundary exactly; "
        "(2) the count difference between filtered and unfiltered source is fully explainable; "
        "(3) boundary edges are correct — records on the first and last day of the reporting period "
        "are included, and records just outside are excluded."
    )
    fb_col      = st.selectbox("Filtered column to validate", cols, key="fb_col")
    fb_exp_min  = st.text_input("Expected minimum value (inclusive boundary)", key="fb_exp_min")
    fb_exp_max  = st.text_input("Expected maximum value (inclusive boundary)", key="fb_exp_max")
    fb_is_date  = st.checkbox("Treat as date field", value=True, key="fb_is_date")
    fb_date_fmt = st.text_input("Date format (if date)", value="%Y-%m-%d", key="fb_date_fmt")

    if st.button("Validate boundaries", key="btn_fb"):
        try:
            if fb_is_date:
                s = pd.to_datetime(df[fb_col].astype(str).str.strip(), format=fb_date_fmt, errors="coerce")
                actual_min_v = s.min()
                actual_max_v = s.max()
                fmt_fn = lambda v: str(v.date()) if pd.notna(v) else "N/A"
            else:
                s = pd.to_numeric(df[fb_col], errors="coerce")
                actual_min_v = s.min()
                actual_max_v = s.max()
                fmt_fn = lambda v: str(v) if pd.notna(v) else "N/A"

            ma, mb = st.columns(2)
            ma.metric("Actual min in output", fmt_fn(actual_min_v))
            mb.metric("Actual max in output", fmt_fn(actual_max_v))

            results = []
            if fb_exp_min.strip():
                exp_min = pd.Timestamp(fb_exp_min.strip()) if fb_is_date else float(fb_exp_min.strip())
                match   = (actual_min_v == exp_min) if pd.notna(actual_min_v) else False
                results.append({"Boundary": "Min", "Expected": str(fb_exp_min.strip()),
                                 "Actual": fmt_fn(actual_min_v), "Match": "✅" if match else "❌"})
            if fb_exp_max.strip():
                exp_max = pd.Timestamp(fb_exp_max.strip()) if fb_is_date else float(fb_exp_max.strip())
                match   = (actual_max_v == exp_max) if pd.notna(actual_max_v) else False
                results.append({"Boundary": "Max", "Expected": str(fb_exp_max.strip()),
                                 "Actual": fmt_fn(actual_max_v), "Match": "✅" if match else "❌"})
            if results:
                st.dataframe(pd.DataFrame(results), use_container_width=True)

            if fb_is_date and fb_exp_min.strip():
                edge_min  = pd.Timestamp(fb_exp_min.strip())
                edge_rows = df[s == edge_min]
                st.metric("Records on first day of period", f"{len(edge_rows):,}",
                          delta="✅ Present" if len(edge_rows) > 0 else "⚠️ None found",
                          delta_color="normal" if len(edge_rows) > 0 else "inverse")
            if fb_is_date and fb_exp_max.strip():
                edge_max  = pd.Timestamp(fb_exp_max.strip())
                edge_rows = df[s == edge_max]
                st.metric("Records on last day of period", f"{len(edge_rows):,}",
                          delta="✅ Present" if len(edge_rows) > 0 else "⚠️ None found",
                          delta_color="normal" if len(edge_rows) > 0 else "inverse")
        except Exception as e:
            st.error(f"Error: {e}")

    # ── 6. Duplicate record count ─────────────────────────────────────────────
    st.markdown("---")
    st.markdown("**6. Duplicate Record Count**")
    st.caption(
        "Document the count of duplicate records and confirm it is zero, "
        "or that any duplicates are expected and explainable. "
        "Use the Data Completeness tab for full drill-down."
    )
    sc_dup_cols = st.multiselect("Columns defining a unique record", cols, key="sc_dup_cols")
    if st.button("Check duplicates", key="btn_sc_dup") and sc_dup_cols:
        n_dup = int(df.duplicated(subset=sc_dup_cols, keep=False).sum())
        st.metric("Duplicate rows", f"{n_dup:,}",
                  delta="✅ Zero duplicates" if n_dup == 0 else f"❌ {n_dup:,} duplicates found",
                  delta_color="normal" if n_dup == 0 else "inverse")
        if n_dup == 0:
            st.success("✅ Duplicate count is zero.")
        else:
            st.warning(f"⚠️ {n_dup:,} duplicate rows found. Go to the Data Completeness tab to drill into them, or document below if expected.")
    st.text_area("Duplicate notes — document any expected duplicates and reason", height=60, key="dup_notes_sanity")

    # ── 7. Financial encoding spot check ─────────────────────────────────────
    st.markdown("---")
    st.markdown("**7. Financial Encoding Spot Check (Overpunch / Scaled)**")
    st.caption(
        "For sources known to use overpunch or scaled encoding (e.g., raw Rx where amounts "
        "are stored as integers requiring ÷100), verify the conversion is correct. "
        "Spot-check 3–5 records by tracing a raw source value through to the output amount and confirming the math."
    )
    sp_col     = st.selectbox("Output amount column to spot-check", cols, key="sp_col")
    sp_divisor = st.number_input("Divisor applied in transform (e.g. 100 for cents→dollars)", min_value=1, value=100, key="sp_divisor")
    sp_raw_val = st.text_input("Raw source value (before conversion)", key="sp_raw_val")
    sp_exp_out = st.text_input("Expected output value (after conversion)", key="sp_exp_out")
    if st.button("Verify conversion", key="btn_sp"):
        if sp_raw_val.strip() and sp_exp_out.strip():
            try:
                raw_v = float(sp_raw_val.strip())
                exp_v = float(sp_exp_out.strip())
                calc  = raw_v / sp_divisor
                if round(calc, 2) == round(exp_v, 2):
                    st.success(f"✅ {raw_v} ÷ {sp_divisor} = {calc:.2f} matches expected {exp_v:.2f}.")
                else:
                    st.error(f"❌ {raw_v} ÷ {sp_divisor} = {calc:.2f} — does NOT match expected {exp_v:.2f}.")
            except ValueError:
                st.error("Enter valid numeric values.")
        s = pd.to_numeric(df[sp_col], errors="coerce")
        ma, mb, mc, md = st.columns(4)
        ma.metric("Min",           f"{s.min():,.2f}"  if s.notna().any() else "N/A")
        mb.metric("Max",           f"{s.max():,.2f}"  if s.notna().any() else "N/A")
        mc.metric("Mean",          f"{s.mean():,.2f}" if s.notna().any() else "N/A")
        md.metric("Negative rows", f"{int((s < 0).sum()):,}")

    # ════════════════════════════════════════════════════════════════════════
    # Medical Claims Reports sub-section
    # ════════════════════════════════════════════════════════════════════════
    st.markdown("---")
    st.markdown("### Medical Claims Reports")

    # ── 8. CPT code formatting ────────────────────────────────────────────────
    st.markdown("**8. CPT Code Formatting**")
    st.caption(
        "Validate that CPT codes from non-standard inputs do not contain irregular formatting "
        "(e.g., random comma placements, extra characters)."
    )
    auto_proc = [c for c in cols if any(x in c.lower() for x in ["proc", "cpt", "hcpcs", "procedure"])]
    proc_col  = st.selectbox("Procedure code column", auto_proc if auto_proc else cols, key="proc_col")
    if st.button("Check CPT formatting", key="btn_cpt_fmt"):
        s   = df[proc_col].astype(str).str.strip()
        bad = s[(s != "") & ~s.str.fullmatch(r'[A-Z0-9]{4,7}')]
        st.metric("Codes with irregular format", f"{len(bad):,}",
                  delta="✅ None" if len(bad) == 0 else f"❌ {len(bad):,}",
                  delta_color="normal" if len(bad) == 0 else "inverse")
        if not bad.empty:
            bad_idx = s[(s != "") & ~s.str.fullmatch(r'[A-Z0-9]{4,7}')].index
            with st.expander("Show irregular code rows"):
                st.dataframe(df.loc[bad_idx].head(50), use_container_width=True)
        else:
            st.success("✅ All non-blank procedure codes match expected format.")

    # ── 9. Procedure code type consistency ────────────────────────────────────
    st.markdown("---")
    st.markdown("**9. Procedure Code Type Consistency**")
    st.caption("Confirm procedure code fields are populated with a consistent code type (CPT vs. ICD). Flag mixed code types in the same field.")
    if st.button("Analyze code types", key="btn_proc"):
        def classify(v):
            v = str(v).strip().upper()
            if not v or v in ("", "NAN"): return "Blank"
            if re.fullmatch(r'\d{5}',       v): return "CPT (5-digit)"
            if re.fullmatch(r'[A-Z]\d{4}',  v): return "HCPCS (letter + 4 digits)"
            if re.fullmatch(r'[A-Z0-9]{7}', v): return "ICD-10-PCS (7-char)"
            if re.fullmatch(r'\d{2,4}',     v): return "ICD-9 (2–4 digit)"
            return "Other / Unknown"

        cat_series = df[proc_col].apply(classify)
        cats = cat_series.value_counts().reset_index()
        cats.columns = ["Code Type", "Count"]
        cats["%"] = (cats["Count"] / total_rows * 100).round(2)
        st.session_state["proc_cats"]      = cats
        st.session_state["proc_series"]    = cat_series
        st.session_state["proc_col_saved"] = proc_col

        n_types = int((cats.loc[cats["Code Type"] != "Blank", "Code Type"]).nunique())
        if n_types > 1:
            st.warning(f"⚠️ {n_types} distinct code types detected — possible mixing of CPT and ICD.")
        elif n_types == 1:
            st.success("✅ Procedure codes appear consistent.")

    if "proc_cats" in st.session_state:
        row = drilldown(st.session_state["proc_cats"], "proc_types",
                        "Click a code type to see example records.")
        if row is not None:
            cat_series = st.session_state["proc_series"]
            res        = df[(cat_series == row["Code Type"]).values].reset_index(drop=True)
            st.markdown(f"#### `{row['Code Type']}` — {len(res):,} rows")
            st.dataframe(res, use_container_width=True)

    # ── 10. Claim adjustment / reversal validation ────────────────────────────
    st.markdown("---")
    st.markdown("**10. Original, Adjustment & Reversal Claim Records**")
    st.caption(
        "Validate that original, adjustment, and reversal claim records are all present "
        "and correctly identified and sequenced in the report logic."
    )
    adj_method = st.radio(
        "How are adjustments/reversals identified in this report?",
        ["Status / type code column", "Sequence / adjustment number", "Original transaction ID column"],
        key="adj_method_sc",
    )

    adj_base_cols = st.multiselect("Base claim ID column(s) — groups related claim rows", cols, key="adj_base_cols_sc")

    if adj_method == "Status / type code column":
        status_col_adj  = st.selectbox("Status / type column", cols, key="adj_status_col_sc")
        reversal_vals   = st.text_input("Reversal / adjustment values (comma-separated)",
                                        value="R,REV,Reversal,VOID,ADJ,Adjustment,Corrected", key="adj_rev_vals_sc")
        original_vals   = st.text_input("Original / paid values (comma-separated)",
                                        value="P,Paid,Approved,A,Original", key="adj_orig_vals_sc")
        if st.button("Run", key="btn_adj_sc"):
            if not adj_base_cols:
                st.warning("Select at least one base claim ID column above.")
            else:
                rev_set  = {v.strip().lower() for v in reversal_vals.split(",") if v.strip()}
                orig_set = {v.strip().lower() for v in original_vals.split(",") if v.strip()}
                tmp      = df.copy()
                tmp["_S_N"]    = tmp[status_col_adj].astype(str).str.strip().str.lower()
                tmp["_IS_REV"] = tmp["_S_N"].isin(rev_set)
                tmp["_IS_ORIG"]= tmp["_S_N"].isin(orig_set)
                n_rev  = int(tmp["_IS_REV"].sum())
                n_orig = int(tmp["_IS_ORIG"].sum())
                n_oth  = total_rows - n_rev - n_orig
                ma, mb, mc = st.columns(3)
                ma.metric("Original / paid rows", f"{n_orig:,}")
                mb.metric("Reversal / adjustment rows", f"{n_rev:,}")
                mc.metric("Other / unmapped rows", f"{n_oth:,}")

                # Reversals with no matching original in same base-ID group
                orig_groups = set(map(tuple, tmp[tmp["_IS_ORIG"]][adj_base_cols].astype(str).values.tolist()))
                tmp["_KEY"]  = list(map(tuple, tmp[adj_base_cols].astype(str).values.tolist()))
                orphaned     = tmp[tmp["_IS_REV"] & ~tmp["_KEY"].isin(orig_groups)]
                st.metric("Reversals with no matching original in file", f"{len(orphaned):,}",
                          delta="✅ None" if len(orphaned) == 0 else f"❌ {len(orphaned):,}",
                          delta_color="normal" if len(orphaned) == 0 else "inverse")
                if not orphaned.empty:
                    with st.expander("Show orphaned reversals"):
                        st.dataframe(orphaned.drop(columns=["_S_N","_IS_REV","_IS_ORIG","_KEY"]).head(50),
                                     use_container_width=True)

                dist = df[status_col_adj].value_counts(dropna=False).reset_index()
                dist.columns = ["Status", "Count"]
                dist["%"] = (dist["Count"] / total_rows * 100).round(2)
                row = drilldown(dist, "adj_status_sc", "Click a status value to see those records.")
                if row is not None:
                    mask = df[status_col_adj].astype(str).str.strip() == str(row["Status"])
                    res  = df[mask].reset_index(drop=True)
                    st.markdown(f"#### Status `{row['Status']}` — {len(res):,} rows")
                    st.dataframe(res, use_container_width=True)

    elif adj_method == "Sequence / adjustment number":
        seq_col      = st.selectbox("Sequence / adjustment number column", cols, key="adj_seq_col_sc")
        seq_orig_val = st.text_input("Value(s) representing the ORIGINAL claim (comma-separated)",
                                     value="1,0,01", key="adj_seq_orig_sc")
        if st.button("Run", key="btn_adj_sc"):
            if not adj_base_cols:
                st.warning("Select at least one base claim ID column above.")
            else:
                orig_vals = {v.strip() for v in seq_orig_val.split(",") if v.strip()}
                tmp       = df.copy()
                tmp["_SEQ"]    = tmp[seq_col].astype(str).str.strip()
                tmp["_IS_ADJ"] = ~tmp["_SEQ"].isin(orig_vals)
                merged = tmp.merge(
                    tmp[~tmp["_IS_ADJ"]][adj_base_cols].drop_duplicates().assign(_HAS_ORIG=True),
                    on=adj_base_cols, how="left",
                )
                adj_rows = merged[merged["_IS_ADJ"]]
                no_orig  = adj_rows[adj_rows["_HAS_ORIG"].isna()]
                ma, mb   = st.columns(2)
                ma.metric("Adjusted / reprocessed rows", f"{len(adj_rows):,}")
                mb.metric("Adjusted rows with no matching original", f"{len(no_orig):,}",
                          delta="✅ None" if len(no_orig) == 0 else f"❌ {len(no_orig):,}",
                          delta_color="normal" if len(no_orig) == 0 else "inverse")
                if not no_orig.empty:
                    with st.expander("Show orphaned adjustments"):
                        st.dataframe(no_orig.drop(columns=["_SEQ","_IS_ADJ","_HAS_ORIG"]).head(50), use_container_width=True)
                else:
                    st.success("✅ Every adjusted claim has a matching original in this file.")

    else:  # Original transaction ID
        orig_col = st.selectbox("Original transaction ID column", cols, key="adj_orig_col_sc")
        null_vals = st.text_input("Values meaning 'no original' (null sentinel, comma-separated)",
                                  value="0,,NULL,null", key="adj_null_vals_sc")
        if st.button("Run", key="btn_adj_sc"):
            null_set = {v.strip() for v in null_vals.split(",") if v.strip()}
            tx_s     = df[adj_base_cols[0]].astype(str).str.strip() if adj_base_cols else pd.Series(dtype=str)
            orig_s   = df[orig_col].astype(str).str.strip()
            non_null      = orig_s[~orig_s.isin(null_set)]
            unmatched_ids = set(non_null) - set(tx_s)
            st.metric("Reversal / adjustment rows (non-null orig ID)", f"{len(non_null):,}")
            st.metric("Unmatched original IDs (no corresponding row in file)", f"{len(unmatched_ids):,}",
                      delta="✅ None" if len(unmatched_ids) == 0 else f"❌ {len(unmatched_ids):,}",
                      delta_color="normal" if len(unmatched_ids) == 0 else "inverse")
            if unmatched_ids:
                with st.expander("Show unmatched reversal rows"):
                    st.dataframe(df[orig_s.isin(unmatched_ids)].head(50), use_container_width=True)
            else:
                st.success("✅ All reversals/adjustments have a matching original claim in this file.")

    # ── 11. Monthly financial aggregation ──────────────────────────────────────
    st.markdown("---")
    st.markdown("**11. Monthly Financial Aggregation vs. Source**")
    st.caption(
        "Aggregate plan paid, billed, and allowed amounts by month (or by week if the report is weekly) "
        "in the final output and compare directly to the same aggregation run against the raw source claims table "
        "using identical date filters and population scope. Investigate any variance."
    )
    agg_date_col = st.selectbox("Date column for aggregation", cols, key="agg_date_col")
    agg_date_fmt = st.text_input("Date format", value="%Y-%m-%d", key="agg_date_fmt")
    agg_period   = st.radio("Aggregate by", ["Month", "Week"], horizontal=True, key="agg_period")
    agg_amt_cols = st.multiselect("Amount columns to aggregate (paid, billed, allowed…)", cols, key="agg_amt_cols")
    if st.button("Generate aggregation", key="btn_agg") and agg_amt_cols:
        try:
            tmp = df.copy()
            tmp["_DATE"] = pd.to_datetime(tmp[agg_date_col].astype(str).str.strip(),
                                          format=agg_date_fmt, errors="coerce")
            tmp = tmp.dropna(subset=["_DATE"])
            tmp["_PERIOD"] = (tmp["_DATE"].dt.to_period("M" if agg_period == "Month" else "W").astype(str))
            for c in agg_amt_cols:
                tmp[c] = pd.to_numeric(tmp[c], errors="coerce")
            agg = (tmp.groupby("_PERIOD")[agg_amt_cols].sum().round(2)
                   .reset_index().rename(columns={"_PERIOD": agg_period}))
            st.session_state["fin_agg_result"] = agg
        except Exception as e:
            st.error(f"Error: {e}")

    if "fin_agg_result" in st.session_state:
        agg = st.session_state["fin_agg_result"]
        st.dataframe(agg, use_container_width=True)
        st.download_button("Download aggregation as CSV",
                           data=agg.to_csv(index=False).encode(),
                           file_name="monthly_aggregation.csv", mime="text/csv")
        st.text_area("Variance notes — document any differences vs. source aggregation",
                     height=60, key="agg_variance_notes")

    # ── 12. Financial field additive check ────────────────────────────────────
    st.markdown("---")
    st.markdown("**12. Financial Field Additive Check**")
    st.caption(
        "Ensure fields that should add up to equal a certain value or the value in another column do. "
        "Example: copay + deductible + coinsurance = member responsibility."
    )
    add_cols  = st.multiselect("Columns to sum (A + B + C…)", cols, key="add_cols")
    add_total = st.selectbox("Should equal this column", cols, key="add_total_col")
    if st.button("Run", key="btn_add_check") and add_cols:
        tmp   = df.copy()
        all_f = list(set(add_cols + [add_total]))
        for c in all_f:
            tmp[c] = pd.to_numeric(tmp[c], errors="coerce")
        row_sums   = tmp[add_cols].sum(axis=1, skipna=False).round(2)
        cmp_vals   = tmp[add_total].round(2)
        valid_mask = tmp[all_f].notna().all(axis=1)
        match_mask = (row_sums == cmp_vals) & valid_mask
        valid_n    = int(valid_mask.sum())
        match_n    = int(match_mask.sum())
        pct        = match_n / valid_n * 100 if valid_n else 0
        ma, mb, mc = st.columns(3)
        ma.metric("Matching rows",          f"{match_n:,}")
        mb.metric("Valid rows (all numeric)", f"{valid_n:,}")
        mc.metric("Match %", f"{pct:.2f}%",
                  delta="✅ 100%" if pct == 100 else f"❌ {100-pct:.2f}% mismatch",
                  delta_color="normal" if pct == 100 else "inverse")
        mismatch = tmp[~match_mask & valid_mask]
        if not mismatch.empty:
            with st.expander("Show mismatched rows (first 50)"):
                st.dataframe(mismatch[all_f].head(50), use_container_width=True)
